import type { InjectionToken } from 'tsyringe'
import type { DataSource } from 'typeorm'
import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm'
import { inject, injectable } from 'tsyringe'
import { TypeOrmRepositoryAdapter } from '@banana-universe/plugin-typeorm'
import type { Repository } from '@banana-universe/ddd'
import { CatalogItem, type CatalogItemProps } from './CatalogItem.js'

// --- persistence port ---
export interface CatalogItemRepository extends Repository<CatalogItem> {
  /** Persist a new catalog item; ID and timestamps are assigned by the database. */
  create(data: Pick<CatalogItemProps, 'name' | 'sku'>): Promise<CatalogItem>
}

export const CatalogItemRepositoryToken = Symbol(
  'CatalogItemRepository',
) as InjectionToken<CatalogItemRepository>

// --- ORM entity ---
// ID generated by @PrimaryGeneratedColumn('uuid'); timestamps by @CreateDateColumn/@UpdateDateColumn.
@Entity('catalog_items')
export class CatalogItemOrmEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @Column({ type: 'varchar', length: 200 })
  name!: string

  @Column({ type: 'varchar', length: 64, unique: true })
  sku!: string

  @CreateDateColumn()
  createdAt!: Date

  @UpdateDateColumn()
  updatedAt!: Date
}

// --- TypeORM repository adapter ---
@injectable()
export class CatalogItemTypeOrmRepository extends TypeOrmRepositoryAdapter<
  CatalogItem,
  CatalogItemOrmEntity
> {
  constructor(@inject('dataSource') dataSource: DataSource) {
    super(dataSource, CatalogItemOrmEntity)
  }

  async create(data: Pick<CatalogItemProps, 'name' | 'sku'>): Promise<CatalogItem> {
    const row = new CatalogItemOrmEntity()
    row.name = data.name
    row.sku = data.sku
    // id: generated by @PrimaryGeneratedColumn('uuid')
    // createdAt / updatedAt: generated by @CreateDateColumn / @UpdateDateColumn
    const saved = await this.repo.save(row)
    return this.toDomain(saved)
  }

  toDomain(orm: CatalogItemOrmEntity): CatalogItem {
    return new CatalogItem({
      id: orm.id,
      name: orm.name,
      sku: orm.sku,
      createdAt: orm.createdAt,
      updatedAt: orm.updatedAt,
    })
  }

  /** Used for updates; only domain fields are mapped — timestamps are managed by the database. */
  toPersistence(domain: CatalogItem): CatalogItemOrmEntity {
    const row = new CatalogItemOrmEntity()
    row.id = domain.id
    row.name = domain.name
    row.sku = domain.sku
    return row
  }
}
