import * as fs from 'fs/promises'
import * as path from 'path'
import chalk from 'chalk'
import { loadBananarc } from './llm/bananarc.js'
import { BANANAJS_AI_RULES_MARKDOWN, BANANAJS_AI_RULES_VERSION } from './llm/bananajs-ai-rules.js'

export type AiContextFormat = 'claude' | 'cursor' | 'copilot' | 'agents' | 'all'

export interface AiContextOptions {
  format?: AiContextFormat
  out?: string
  dryRun?: boolean
  cwd?: string
}

interface ModuleEntry {
  name: string
  path: string
}

/** Scan src/modules for createModule exports (same logic as ai-wire). */
async function discoverModules(srcRoot: string): Promise<ModuleEntry[]> {
  const modulesDir = path.join(srcRoot, 'modules')
  const out: ModuleEntry[] = []
  let dirs: Awaited<ReturnType<typeof fs.readdir>>
  try {
    dirs = await fs.readdir(modulesDir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const d of dirs) {
    if (!d.isDirectory()) continue
    const indexFile = path.join(modulesDir, d.name, 'index.ts')
    let raw: string
    try {
      raw = await fs.readFile(indexFile, 'utf-8')
    } catch {
      continue
    }
    if (/createModule/.test(raw)) {
      const nameMatch = raw.match(/export\s+const\s+(\w+Module)\s*=/)
      out.push({
        name: nameMatch ? nameMatch[1] : d.name,
        path: `src/modules/${d.name}`,
      })
    }
  }
  return out
}

/** Read package.json dependencies keys for plugin detection. */
async function readDependencyKeys(cwd: string): Promise<string[]> {
  try {
    const raw = await fs.readFile(path.join(cwd, 'package.json'), 'utf-8')
    const pkg = JSON.parse(raw) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> }
    return [
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]
  } catch {
    return []
  }
}

function pluginListMarkdown(deps: string[]): string {
  const plugins = deps.filter((d) => d.startsWith('@banana-universe/plugin-'))
  if (plugins.length === 0) return 'None detected'
  return plugins.map((p) => `- ${p}`).join('\n')
}

function moduleListMarkdown(modules: ModuleEntry[]): string {
  if (modules.length === 0) return 'None detected in src/modules/'
  return modules.map((m) => `- \`${m.name}\` → \`${m.path}\``).join('\n')
}

function buildContextBody(
  config: Awaited<ReturnType<typeof loadBananarc>>,
  modules: ModuleEntry[],
  plugins: string[],
): string {
  const orm = config.generate?.defaultOrm ?? config.generate?.preset ?? 'typeorm'
  const apiPrefix = config.project?.apiPrefix ?? '(not set)'
  const bootstrap = config.project?.bootstrap ?? 'src/bootstrap.ts'

  return `## Project context

| Setting | Value |
|---|---|
| ORM | \`${orm}\` |
| API prefix | \`${apiPrefix}\` |
| Bootstrap | \`${bootstrap}\` |

## Discovered modules

${moduleListMarkdown(modules)}

## Installed plugins

${pluginListMarkdown(plugins)}

## BananaJS AI rules (v${BANANAJS_AI_RULES_VERSION})

${BANANAJS_AI_RULES_MARKDOWN}`
}

// ─── Format builders ──────────────────────────────────────────────────────────

function buildClaude(body: string): string {
  return `# BananaJS project context

This file is auto-generated by \`bananajs ai context\`. Do not edit manually.

${body}
`
}

function buildCursor(body: string): string {
  return `---
description: BananaJS project conventions for Cursor
globs: ["src/**/*.ts"]
alwaysApply: true
---

# BananaJS project context

This file is auto-generated by \`bananajs ai context\`. Do not edit manually.

${body}
`
}

function buildCursorLegacy(body: string): string {
  return `# BananaJS project context (.cursorrules — legacy)

This file is auto-generated by \`bananajs ai context\` for backwards compatibility.
Prefer \`.cursor/rules/bananajs.mdc\` in Cursor versions that support it.

${body}
`
}

function buildCopilot(body: string): string {
  return `# BananaJS project context

This file is auto-generated by \`bananajs ai context\`. Do not edit manually.

${body}
`
}

function buildAgents(body: string): string {
  return `# BananaJS project context for AI agents

This file is auto-generated by \`bananajs ai context\`. Do not edit manually.
Place at the project root so agent CLIs (OpenAI Codex, Claude Code, etc.) load it automatically.

${body}
`
}

interface OutputFile {
  relativePath: string
  content: string
}

function buildOutputFiles(body: string, format: AiContextFormat): OutputFile[] {
  const files: OutputFile[] = []
  if (format === 'claude' || format === 'all') {
    files.push({ relativePath: 'CLAUDE.md', content: buildClaude(body) })
  }
  if (format === 'cursor' || format === 'all') {
    files.push({ relativePath: path.join('.cursor', 'rules', 'bananajs.mdc'), content: buildCursor(body) })
    files.push({ relativePath: '.cursorrules', content: buildCursorLegacy(body) })
  }
  if (format === 'copilot' || format === 'all') {
    files.push({ relativePath: path.join('.github', 'copilot-instructions.md'), content: buildCopilot(body) })
  }
  if (format === 'agents' || format === 'all') {
    files.push({ relativePath: 'AGENTS.md', content: buildAgents(body) })
  }
  return files
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function runAiContext(opts: AiContextOptions): Promise<void> {
  const cwd = opts.cwd ?? process.cwd()
  const format = opts.format ?? 'all'
  const outDir = opts.out ? path.resolve(cwd, opts.out) : cwd
  const dryRun = opts.dryRun ?? false

  const config = await loadBananarc(cwd)
  const srcRoot = path.join(cwd, 'src')
  const [modules, deps] = await Promise.all([
    discoverModules(srcRoot),
    readDependencyKeys(cwd),
  ])

  const body = buildContextBody(config, modules, deps)
  const outputFiles = buildOutputFiles(body, format)

  console.log(chalk.bold.blue(`\nGenerating AI context files (format: ${format})\n`))
  console.log(chalk.dim(`  Modules found: ${modules.length} · Plugins found: ${deps.filter((d) => d.startsWith('@banana-universe/plugin-')).length}`))
  console.log('')

  for (const file of outputFiles) {
    const absPath = path.join(outDir, file.relativePath)
    if (dryRun) {
      console.log(chalk.cyan(`[dry-run] Would write: ${file.relativePath}`))
      console.log(chalk.gray('--- preview (first 5 lines) ---'))
      const preview = file.content.split('\n').slice(0, 5).join('\n')
      console.log(chalk.gray(preview))
      console.log('')
    } else {
      await fs.mkdir(path.dirname(absPath), { recursive: true })
      await fs.writeFile(absPath, file.content, 'utf-8')
      console.log(chalk.green(`  ✔ ${file.relativePath}`))
    }
  }

  if (!dryRun) {
    console.log('')
    console.log(chalk.bold('Done.'))
    console.log(chalk.dim('Commit these files to share BananaJS conventions with your team\'s IDE agents.'))
  }
}
