/**
 * Declarative app scaffolds: each preset is data (id, labels) plus a pure function
 * that returns relative paths and file contents — no git clone or remote templates.
 */

/** Keep dependency ranges aligned with published @banana-universe packages. */
export const SCAFFOLD_VERSIONS = {
  bananajs: '^0.6.0',
  ddd: '^0.1.0',
  pluginMongoose: '^0.1.0',
  pluginTypeorm: '^0.1.0',
} as const

export type AppPresetId = 'mongodb' | 'sql'

export type ScaffoldContext = {
  /** Display name / folder name */
  appName: string
  /** package.json "name" field (npm-safe) */
  packageName: string
}

export type ScaffoldFile = { relativePath: string; content: string }

export type AppPreset = {
  id: AppPresetId
  /** Shown in interactive prompt */
  promptLabel: string
  description: string
  buildFiles: (ctx: ScaffoldContext) => ScaffoldFile[]
}

const sharedTsconfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: 'dist',
        rootDir: 'src',
        strict: true,
        experimentalDecorators: true,
        skipLibCheck: true,
        types: ['node'],
      },
      include: ['src/**/*.ts'],
    },
    null,
    2,
  )

const sharedGitignore = (): string =>
  ['node_modules/', 'dist/', '.env', '*.log', '.DS_Store'].join('\n') + '\n'

function mongoPackageJson(ctx: ScaffoldContext): string {
  return JSON.stringify(
    {
      name: ctx.packageName,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: `BananaJS app (${ctx.appName}) — MongoDB / Mongoose`,
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/main.js',
      },
      dependencies: {
        '@banana-universe/bananajs': SCAFFOLD_VERSIONS.bananajs,
        '@banana-universe/ddd': SCAFFOLD_VERSIONS.ddd,
        '@banana-universe/plugin-mongoose': SCAFFOLD_VERSIONS.pluginMongoose,
        tsyringe: '^4.8.0',
        express: '^4.21.2',
        mongoose: '^8.9.0',
        'reflect-metadata': '^0.2.2',
        zod: '^3.24.0',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        typescript: '~5.7.2',
      },
    },
    null,
    2,
  )
}

function sqlPackageJson(ctx: ScaffoldContext): string {
  return JSON.stringify(
    {
      name: ctx.packageName,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: `BananaJS app (${ctx.appName}) — PostgreSQL / TypeORM`,
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/main.js',
      },
      dependencies: {
        '@banana-universe/bananajs': SCAFFOLD_VERSIONS.bananajs,
        '@banana-universe/ddd': SCAFFOLD_VERSIONS.ddd,
        '@banana-universe/plugin-typeorm': SCAFFOLD_VERSIONS.pluginTypeorm,
        tsyringe: '^4.8.0',
        express: '^4.21.2',
        pg: '^8.13.1',
        'reflect-metadata': '^0.2.2',
        typeorm: '^0.3.20',
        zod: '^3.24.0',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        typescript: '~5.7.2',
      },
    },
    null,
    2,
  )
}

function mongoReadme(ctx: ScaffoldContext): string {
  return `# ${ctx.appName}

Generated by \`bananajs new\` (MongoDB / Mongoose preset).

## Setup

\`\`\`bash
npm install
cp .env.example .env   # set DATABASE_URL
npm run build && npm start
\`\`\`

## Endpoints

- \`GET /articles/healthz\` — liveness
- \`POST /articles\` — create article (JSON body: \`title\`, \`body\`)
`
}

function sqlReadme(ctx: ScaffoldContext): string {
  return `# ${ctx.appName}

Generated by \`bananajs new\` (PostgreSQL / TypeORM preset).

## Setup

\`\`\`bash
npm install
cp .env.example .env   # set DATABASE_URL for PostgreSQL
npm run build && npm start
\`\`\`

## Endpoints

- \`GET /healthz\` — liveness

The scaffold includes a minimal \`NoteEntity\` so TypeORM can synchronize schema (\`synchronize: true\` — disable in production).
`
}

function buildMongoFiles(ctx: ScaffoldContext): ScaffoldFile[] {
  return [
    { relativePath: 'package.json', content: mongoPackageJson(ctx) },
    { relativePath: 'tsconfig.json', content: sharedTsconfig() },
    { relativePath: '.gitignore', content: sharedGitignore() },
    {
      relativePath: '.env.example',
      content: 'DATABASE_URL=mongodb://127.0.0.1:27017/bananajs_app\nPORT=3000\n',
    },
    { relativePath: 'README.md', content: mongoReadme(ctx) },
    {
      relativePath: 'src/main.ts',
      content: `import 'reflect-metadata'
import { createMongoApp } from './bootstrap.js'

const port = Number(process.env.PORT ?? 3000)
const banana = await createMongoApp()
banana.getInstance().listen(port, () => {
  console.log(\`${ctx.appName} listening on \${port}\`)
})
`,
    },
    {
      relativePath: 'src/bootstrap.ts',
      content: `import 'reflect-metadata'
import mongoose from 'mongoose'
import {
  BananaApp,
  type BananaPlugin,
  defineBananaAppOptions,
  defineBananaControllers,
} from '@banana-universe/bananajs'
import { MongoosePlugin } from '@banana-universe/plugin-mongoose'
import { ArticleController } from './article.controller.js'
import { getArticleModel, ArticleModelToken } from './article.model.js'

export async function createMongoApp(): Promise<BananaApp> {
  const uri = process.env.DATABASE_URL ?? 'mongodb://127.0.0.1:27017/bananajs_app'
  const connection = await mongoose.createConnection(uri).asPromise()

  return BananaApp.create(
    defineBananaAppOptions({
      controllers: defineBananaControllers(ArticleController),
      providers: [
        { token: ArticleModelToken, useFactory: () => getArticleModel(connection) },
        ArticleController,
      ],
      plugins: [MongoosePlugin(connection) as BananaPlugin],
      logger: false,
      gracefulShutdown: false,
      rateLimit: false,
      requestId: false,
      security: { helmet: false, cors: false },
    }),
  )
}
`,
    },
    {
      relativePath: 'src/article.controller.ts',
      content: `import 'reflect-metadata'
import type { Request, Response } from 'express'
import type { Model } from 'mongoose'
import { inject, injectable } from 'tsyringe'
import { BaseController, Body, Controller, Get, Post, Public } from '@banana-universe/bananajs'
import type { ArticleDoc } from './article.model.js'
import { ArticleModelToken } from './article.model.js'
import { CreateArticleSchema } from './article.schema.js'

@injectable()
@Controller('articles')
export class ArticleController extends BaseController {
  constructor(@inject(ArticleModelToken) private readonly articleModel: Model<ArticleDoc>) {
    super()
  }

  @Get('healthz')
  @Public()
  health(_req: Request, res: Response) {
    return this.ok(res, 'ok', { status: 'up' })
  }

  @Post('')
  @Body(CreateArticleSchema)
  async create(req: Request, res: Response) {
    const { title, body } = req.body as { title: string; body: string }
    const created = await this.articleModel.create({ title, body })
    return this.ok(res, 'created', { id: String(created._id), title: created.title })
  }
}
`,
    },
    {
      relativePath: 'src/article.model.ts',
      content: `import type { InjectionToken } from 'tsyringe'
import { Schema, type Connection, type HydratedDocument, type Model } from 'mongoose'

export type ArticleDoc = HydratedDocument<{
  title: string
  body: string
}>

export const ArticleModelToken = Symbol('ArticleModel') as InjectionToken<Model<ArticleDoc>>

const articleSchema = new Schema(
  {
    title: { type: String, required: true },
    body: { type: String, required: true },
  },
  { collection: 'articles' },
)

export function getArticleModel(connection: Connection) {
  const existing = connection.models['Article'] as Model<ArticleDoc> | undefined
  return existing ?? connection.model<ArticleDoc>('Article', articleSchema)
}
`,
    },
    {
      relativePath: 'src/article.schema.ts',
      content: `import { z } from 'zod'

export const CreateArticleSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().min(1).max(10000),
})
`,
    },
  ]
}

function buildSqlFiles(ctx: ScaffoldContext): ScaffoldFile[] {
  return [
    { relativePath: 'package.json', content: sqlPackageJson(ctx) },
    { relativePath: 'tsconfig.json', content: sharedTsconfig() },
    { relativePath: '.gitignore', content: sharedGitignore() },
    {
      relativePath: '.env.example',
      content: 'DATABASE_URL=postgres://postgres:postgres@localhost:5432/bananajs_app\nPORT=3000\n',
    },
    { relativePath: 'README.md', content: sqlReadme(ctx) },
    {
      relativePath: 'src/main.ts',
      content: `import 'reflect-metadata'
import { createSqlApp } from './bootstrap.js'

const port = Number(process.env.PORT ?? 3000)
const banana = await createSqlApp()
banana.getInstance().listen(port, () => {
  console.log(\`${ctx.appName} listening on \${port}\`)
})
`,
    },
    {
      relativePath: 'src/bootstrap.ts',
      content: `import 'reflect-metadata'
import {
  BananaApp,
  type BananaPlugin,
  defineBananaAppOptions,
  defineBananaControllers,
} from '@banana-universe/bananajs'
import { TypeOrmPlugin } from '@banana-universe/plugin-typeorm'
import { HealthController } from './health.controller.js'
import { NoteEntity } from './note.entity.js'

export async function createSqlApp(): Promise<BananaApp> {
  return BananaApp.create(
    defineBananaAppOptions({
      controllers: defineBananaControllers(HealthController),
      plugins: [TypeOrmPlugin(buildTypeOrmOptions()) as BananaPlugin],
      logger: false,
      gracefulShutdown: false,
      rateLimit: false,
      requestId: false,
      security: { helmet: false, cors: false },
    }),
  )
}

function buildTypeOrmOptions(): Record<string, unknown> {
  return {
    type: 'postgres',
    url: process.env.DATABASE_URL ?? 'postgres://postgres:postgres@localhost:5432/bananajs_app',
    entities: [NoteEntity],
    synchronize: true,
  }
}
`,
    },
    {
      relativePath: 'src/health.controller.ts',
      content: `import 'reflect-metadata'
import type { Request, Response } from 'express'
import { BaseController, Controller, Get, Public } from '@banana-universe/bananajs'

@Controller('')
export class HealthController extends BaseController {
  @Get('healthz')
  @Public()
  health(_req: Request, res: Response) {
    return this.ok(res, 'ok', { status: 'up' })
  }
}
`,
    },
    {
      relativePath: 'src/note.entity.ts',
      content: `import 'reflect-metadata'
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm'

@Entity({ name: 'notes' })
export class NoteEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string

  @Column({ type: 'varchar', length: 200 })
  title!: string
}
`,
    },
  ]
}

export const APP_PRESETS: AppPreset[] = [
  {
    id: 'mongodb',
    promptLabel: 'MongoDB',
    description: 'Mongoose plugin, sample Article API',
    buildFiles: buildMongoFiles,
  },
  {
    id: 'sql',
    promptLabel: 'SQL',
    description: 'TypeORM + PostgreSQL, health check + minimal entity',
    buildFiles: buildSqlFiles,
  },
]

export function getPresetById(id: string): AppPreset | undefined {
  return APP_PRESETS.find((p) => p.id === id)
}

export function npmPackageNameFromAppName(appName: string): string {
  const slug = appName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_.]+/g, '-')
    .replace(/^-+|-+$/g, '')
  if (slug.length === 0) return 'bananajs-app'
  if (/^\d/.test(slug)) return `app-${slug}`
  return slug
}
